title: Chris Bosco's I.T. & Cybersecurity Project Blog
title: (A Work In Progress)

description: To showcase my skills to my future employer :)
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
