title: Chris Bosco's I.T. & Cybersecurity Project Blog
description: A work in progress,to showcase my skills to my future employer :)
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
